sudo: required
services:
    - docker

before_install:
    - docker build -t i11f2jz8e7/docker-react-test1 -f Dockerfile.dev ./

script:
    - docker run i11f2jz8e7/docker-react-test1 npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "docker-react-test1"
    env: "DockerReactTest1-env"
    bucket_name: ".elasticbeanstalk"
    on:
        branch: master
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY