sudo: required
services:
    - docker

before_install:
    - docker build -t i11f2jz8e7/docker-react-test1 -f Dockerfile.dev ./

script:
    - docker run i11f2jz8e7/docker-react-test1 npm run test -- --coverage